### ISSUE TITLE
Can't go back to sorting by karma

### ISSUE THREAD

**Issue by dlaz** [DLu/askbot_crawler#6]
Users page appears to be sorted by karma at load. If I sort by something else, there's no way to get back to sorting by karma.

**Comment by DLu** [comment]
It's never sorted by karma. It's sorted by Questions Answered.

**Comment by dlaz** [comment]
Ah, got it. I think I was confused because it initially shows up being sorted by ?, and then once loading is finished, it gets resorted in JS.
